name: sign

on:
  pull_request:
    paths:
      - 'signed/*'

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/github-script@0.2.0
      with:
        github-token: ${{github.token}}
        script: |
          try {
            const { data: files } = await github.request(`${context.payload.pull_request.url}/files`)
            const signs = files.filter(f => f.status === 'added')
            if (signs.length > 1)
              throw new Error('Just one file per PR allowed')
            
            if (signs.length == 1) {
              const { data: content } = await github.request(signs[0].raw_url)
              const parts = content.split('|')
              
              if (parts.length != 2)
                throw new Error('Too many vertical bars')

              if (content.match(/\r|\n/g).length > 1)
                throw new Error('Too many lines')
              
              await github.issues.createComment({...context.issue, body: 'Thanks for your signature! 🎉'})
              await github.issues.update({...context.issue, labels: ['correct']})
              # await github.pulls.merge({...context.issue})
            }
          } catch (error) {
            await github.issues.createComment({...context.issue, body: error.message})
            await github.issues.update({...context.issue, labels: ['incorrect']})
            throw 'build failed'
          }
